In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [12]:
model = keras.Sequential(
    [
        layers.Dense(2, activation='relu', name='layer1'),
        layers.Dense(3, activation='relu', name='layer2'),
        layers.Dense(4, activation='relu', name='layer3'),
        layers.Dense(5, name='layer4')
    ]
)

In [13]:
x = tf.ones((3,3))

In [14]:
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [15]:
y = model(x)

In [16]:
print(y)

tf.Tensor(
[[ 0.0539878  -0.04829716  0.24576062  0.0310768   0.23340268]
 [ 0.0539878  -0.04829716  0.24576062  0.0310768   0.23340268]
 [ 0.0539878  -0.04829716  0.24576062  0.0310768   0.23340268]], shape=(3, 5), dtype=float32)


The above model is equivalent to running the following

In [17]:
layer1 = layers.Dense(2, activation='relu', name='layer1')
layer2 = layers.Dense(3, activation='relu', name='layer2')
layer3 = layers.Dense(4, activation='relu', name='layer3')
layer4 = layers.Dense(5, name='layer5')

x = tf.ones((3, 3))
y = layer4(layer3(layer2(layer1(x))))

print(y)

tf.Tensor(
[[-0.27878442 -0.05031079  0.14792162  0.09124458  0.28458947]
 [-0.27878442 -0.05031079  0.14792162  0.09124458  0.28458947]
 [-0.27878442 -0.05031079  0.14792162  0.09124458  0.28458947]], shape=(3, 5), dtype=float32)


In [18]:
model = keras.Sequential(
    [
        layers.Dense(2, activation='relu'),
        layers.Dense(3, activation='relu'),
        layers.Dense(4)
    ]
)

In [20]:
# this doesn't work until you have an input shape
# model.weights

In [22]:
tf.ones((2,4))

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [29]:
x = tf.ones((1,4))

In [30]:
y = model(x)

In [31]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[-0.581167  , -0.20612979],
        [ 0.06313205, -0.50996685],
        [ 0.4178636 ,  0.723223  ],
        [ 0.31078696,  0.87180567]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(2, 3) dtype=float32, numpy=
 array([[ 0.16471732, -1.0601327 , -0.63780713],
        [-0.35976964, -0.7505251 , -0.75962627]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_2/kernel:0' shape=(3, 4) dtype=float32, numpy=
 array([[-0.2879591 , -0.47623438,  0.57450986,  0.64882326],
        [-0.7813819 ,  0.24973965, -0.7782327 ,  0.43146253],
        [-0.00156587,  0.3502214 ,  0.90590763,  0.34140086]],
       dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [32]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2)                 10        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 9         
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 16        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


In [45]:
model = keras.Sequential(
    [
        layers.Dense(2, activation='relu', input_shape=(4,)),
        layers.Dense(3, activation='relu'),
        layers.Dense(4)
    ]
)

In [39]:
x = tf.ones((2, 4))

In [46]:
model.weights

[<tf.Variable 'dense_9/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[ 0.7338567 ,  0.5421443 ],
        [-0.81668735,  0.40352726],
        [-0.1645081 ,  0.5238333 ],
        [-0.38811922, -0.85572386]], dtype=float32)>,
 <tf.Variable 'dense_9/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_10/kernel:0' shape=(2, 3) dtype=float32, numpy=
 array([[-0.2427029 ,  0.00524044, -0.5441915 ],
        [-0.72154546,  0.6884419 ,  0.28115404]], dtype=float32)>,
 <tf.Variable 'dense_10/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_11/kernel:0' shape=(3, 4) dtype=float32, numpy=
 array([[-0.6976719 ,  0.24260509, -0.23377955, -0.1316995 ],
        [-0.2679174 , -0.15584677,  0.7225083 ,  0.6356983 ],
        [ 0.0628404 , -0.62553024,  0.25589395, -0.05952209]],
       dtype=float32)>,
 <tf.Variable 'dense_11/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]